"""add_timezone_to_datetime_columns

Revision ID: f7e2f04f0ecf
Revises: b7bc85e704ff
Create Date: 2025-11-21 20:36:08.553349

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7e2f04f0ecf"
down_revision = "b7bc85e704ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "due_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_tasks_due_date"), table_name="tasks", postgresql_where="(due_date IS NOT NULL)"
    )
    op.drop_index(
        op.f("idx_tasks_priority"), table_name="tasks", postgresql_where="(priority IS NOT NULL)"
    )
    op.drop_index(
        op.f("idx_tasks_session_id"),
        table_name="tasks",
        postgresql_where="(session_id IS NOT NULL)",
    )
    op.drop_index(op.f("idx_tasks_status"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_updated_at"), table_name="tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_tasks_updated_at"), "tasks", [sa.literal_column("updated_at DESC")], unique=False
    )
    op.create_index(op.f("idx_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(
        op.f("idx_tasks_session_id"),
        "tasks",
        ["session_id"],
        unique=False,
        postgresql_where="(session_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_tasks_priority"),
        "tasks",
        ["priority"],
        unique=False,
        postgresql_where="(priority IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_tasks_due_date"),
        "tasks",
        ["due_date"],
        unique=False,
        postgresql_where="(due_date IS NOT NULL)",
    )
    op.alter_column(
        "tasks",
        "completed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "due_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
