"""create_tasks_table

Revision ID: b7bc85e704ff
Revises:
Create Date: 2025-11-21 19:50:55.177960

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7bc85e704ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("priority", sa.Enum("HIGH", "MEDIUM", "LOW", name="taskpriority"), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create indexes for efficient querying
    op.create_index(
        "idx_tasks_updated_at",
        "tasks",
        ["updated_at"],
        unique=False,
        postgresql_ops={"updated_at": "DESC"},
    )
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    op.create_index(
        "idx_tasks_session_id",
        "tasks",
        ["session_id"],
        unique=False,
        postgresql_where=sa.text("session_id IS NOT NULL"),
    )
    op.create_index(
        "idx_tasks_due_date",
        "tasks",
        ["due_date"],
        unique=False,
        postgresql_where=sa.text("due_date IS NOT NULL"),
    )
    op.create_index(
        "idx_tasks_priority",
        "tasks",
        ["priority"],
        unique=False,
        postgresql_where=sa.text("priority IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes before dropping table
    op.drop_index("idx_tasks_priority", table_name="tasks")
    op.drop_index("idx_tasks_due_date", table_name="tasks")
    op.drop_index("idx_tasks_session_id", table_name="tasks")
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_updated_at", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
