"""add task_batches table and batch_id to tasks

Revision ID: 89b9a28536f6
Revises: f7e2f04f0ecf
Create Date: 2025-12-05 20:23:29.734451

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "89b9a28536f6"
down_revision = "f7e2f04f0ecf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("batch_id", sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_tasks_batch_id", "tasks", "task_batches", ["batch_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_batch_id", "tasks", type_="foreignkey")
    op.drop_column("tasks", "batch_id")
    op.drop_table("task_batches")
    # ### end Alembic commands ###
