"""add_reason_to_task_batches

Revision ID: 71e2d999a714
Revises: 89b9a28536f6
Create Date: 2025-12-05 12:13:16.884471

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "71e2d999a714"
down_revision = "89b9a28536f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_batches", sa.Column("reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_batches", "reason")
    # ### end Alembic commands ###
